### ISSUE TITLE
Subtitles missing in CDN

### ISSUE THREAD

**Issue by abcdev** [voc/voctoweb#463] opened 2020-04-20 10:36 UTC
It seems that all subtitles have gone missing or the `recording_url` links for subtitles are outdated.

**Why?**
When querying the "BahnMining - Pünktlichkeit ist eine Zier" event ( `https://api.media.ccc.de/public/events/56e58bc1-1a30-4eae-a81b-78cf86732865` ) the following subtitle recording is returned:

```
{
    "size": null,
    "length": null,
    "mime_type": "application/x-subrip",
    "language": "deu",
    "filename": "36c3-10652-deu-eng-BahnMining_-_Puenktlichkeit_ist_eine_Zier.de.srt",
    "state": "new",
    "folder": "",
    "high_quality": true,
    "width": null,
    "height": null,
    "updated_at": "2020-01-03T19:24:46.951+01:00",
    "recording_url": "https://cdn.media.ccc.de/congress/2019/36c3-10652-deu-eng-BahnMining_-_Puenktlichkeit_ist_eine_Zier.de.srt",
    "url": "https://api.media.ccc.de/public/recordings/44561",
    "event_url": "https://api.media.ccc.de/public/events/56e58bc1-1a30-4eae-a81b-78cf86732865",
    "conference_url": "https://api.media.ccc.de/public/conferences/36c3"
}
```

But `https://cdn.media.ccc.de/congress/2019/36c3-10652-deu-eng-BahnMining_-_Puenktlichkeit_ist_eine_Zier.de.srt` will result in a 404.

_Maybe a hiccup?_ After trying out the same on different events from different congresses/conferences and none returned a working subtitle link, I took a look at the CDN itself:

The CDN does not provide any subtitle files at the path without the file component eg. [https://cdn.media.ccc.de/congress/2019](https://cdn.media.ccc.de/congress/2019)

To me it looks like the sync of #383 failed and made the links invalid or cleaned the CDN (cdn.media.ccc.de) of all subtitles. Can't tell from my point of view.

**Comment by saerdnaer** [comment] 2020-05-03 15:44
TODO:
Add redirects to https://ftp.agdsn.de/pub/mirrors/c3subtitles/ and  https://mirror.selfnet.de/c3subtitles/ to cdn.media.ccc.de webserver config

The due to CORS, the web player currently accesses the subtitles via a proxy_pass rule at app.media.ccc.de, c.f.
```
 location /srt {
    proxy_pass https://mirror.selfnet.de/c3subtitles;
  }
```
For your example this would be https://media.ccc.de/srt/congress/2019/36c3-10652-deu-eng-BahnMining_-_Puenktlichkeit_ist_eine_Zier.de.srt – so yes, the API currently exposes the wrong URLs.

**Comment by lukas2511** [comment] 2020-05-03 18:22
Should be fixed

**Comment by saerdnaer** [comment] 2020-05-03 18:47
confirmed, fixed: https://cdn.media.ccc.de/congress/2019/36c3-10652-deu-eng-BahnMining_-_Puenktlichkeit_ist_eine_Zier.de.srt now redirects to a mirror - Thx!

**Closed by saerdnaer** 2020-05-03 18:47 UTC
